# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# This is mainly taken from
# https://vsupalov.com/build-docker-image-with-circle-ci-2-push-to-google-container-registry/
# and adapted to our needs. Thanks for the awesome preparation.
version: 2.1
workflows:
  test-and-build-image:
    jobs:
      - test-locally
      - push-image:
          requires:
            - test-locally
jobs:
  test-locally:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache in a multiline string,
            # where the second line will be separated by a space from the first.
            - v1-dependencies-{{ checksum "Dockerfile" }}
              {{ checksum "entrypoint.sh" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-


      - run: npm install .

      - save_cache:
          paths:
            - node_modules
          key: >-
            v1-dependencies-{{ checksum "Dockerfile" }}
            {{ checksum "entrypoint.sh" }}

      # Run tests!
      - run: npm test

      # This section builds the image and uploads it to hub.docker.com and is
      # taken from
      # https://circleci.com/docs/2.0/building-docker-images/#overview
      - setup_remote_docker:
          docker_layer_caching: true

      # Install Docker into the image.
      - run:
          name: Install Docker client.
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin


  push-image:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # Specify the unique identifier for the cache in a multiline string,
            # where the second line will be separated by a space from the first.
            - v1-dependencies-{{ checksum "Dockerfile" }}
              {{ checksum "entrypoint.sh" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-

      # This section builds the image and uploads it to hub.docker.com and is
      # taken from
      # https://circleci.com/docs/2.0/building-docker-images/#overview
      - setup_remote_docker:
          docker_layer_caching: true

      # Build and push image.
      - run:
        name: Build and push image.
        command: |
          TAG=$CIRCLE_BRANCH
          docker build -t bludoc/etherpad-lite:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push bludoc/etherpad-lite:$TAG
